# ----------------------------
# Learning git Action
# ----------------------------

name: My-GitHub-Action-tutorial

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: [ubuntu-latest]

    steps:
      - name: Print message from testing job
        run : echo "Hello World"

      - name: Execute multiple messages
        run : |
          echo "Hello msg 1"
          echo "Hello msg 2"

      - name: list current folder
        run : ls -la
        
      - name: Clone my repo
        uses: actions/checkout@v1
      
      - name: list folder after cloning git repo
        run : ls -la
        
  deploy:
    runs-on: [ubuntu-latest]
    needs: [testing]

    steps:
      - name: Print message from deploy job
        run: echo "Project Deployed msg"

      - name: list current folder
        run : ls -la
    
